name: Update Bookeo Data

on:
  schedule:
    - cron: '0 * * * *' # S'exécute au début de chaque heure
  workflow_dispatch:   # Ce déclencheur permet de cliquer sur "Run workflow" manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Scraper
        run: node scraper.js
